export const ALL_RPODUCT_REQUEST = "ALL_RPODUCT_REQUEST";
export const ALL_RPODUCT_SUCCESS = "ALL_RPODUCT_SUCCESS";
export const ALL_RPODUCT_FAIL = "ALL_RPODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
